apiVersion: v1
kind: Pod
metadata:
  name: lab-pod
  labels:
    name: lab-pod
spec:
  containers:
  - name: lab-pod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    #ports:
    #  - containerPort: <Port>
